### ISSUE TITLE
Cant run background_job

### ISSUE THREAD

**Issue by tilight** [matiasdelellis/facerecognition#199]
```
1/10 - Executing task CheckRequirementsTask (Check all requirements)
An unhandled exception has been thrown:
TypeError: Return value of OCA\FaceRecognition\Helper\MemoryLimits::getTotalMemoryLinux() must be of the type int, float returned in /var/www/html/cloud/apps/facerecognition/lib/Helper/MemoryLimits.php:82
Stack trace:
#0 /var/www/html/cloud/apps/facerecognition/lib/Helper/MemoryLimits.php(56): OCA\FaceRecognition\Helper\MemoryLimits::getTotalMemoryLinux()
#1 /var/www/html/cloud/apps/facerecognition/lib/BackgroundJob/Tasks/CheckRequirementsTask.php(82): OCA\FaceRecognition\Helper\MemoryLimits::getAvailableMemory()
#2 /var/www/html/cloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(115): OCA\FaceRecognition\BackgroundJob\Tasks\CheckRequirementsTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#3 /var/www/html/cloud/apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(0, false, NULL, NULL)
#4 /var/www/html/cloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/cloud/3rdparty/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/cloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/cloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/cloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/cloud/console.php(97): OC\Console\Application->run()
#10 /var/www/html/cloud/occ(11): require_once('/var/www/html/c...')
```

**Comment by matiasdelellis** [comment]
Hi @tilight 
Thank you for testing the application and reporting. . 

It is strange because it is a simple code that was tested and did not change..  On what system you're running? You can share the content of your `/proc/meminfo`?

**Comment by matiasdelellis** [comment]
HI @tilight 
https://github.com/matiasdelellis/facerecognition/pull/211

**Comment by matiasdelellis** [comment]
It should be fixed. In any case I invite you to reopen it.. :smile:
