### ISSUE TITLE
face:setup error

### ISSUE THREAD

**Issue by ltotsas** [matiasdelellis/facerecognition#235]
I am trying to install the model but i get an error

### Actual behaviour

`Downloading: https://github.com/davisking/dlib-models/raw/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2 on /tmp/oc_tmp_6HxAhp-folder-.facerecognition/mmod_human_face_detector.dat.bz2
Download 694687 bytes
Decompresing: /tmp/oc_tmp_6HxAhp-folder-.facerecognition/mmod_human_face_detector.dat.bz2 on /var/www/nextcloud/data/appdata_ocs5evl25flu/facerecognition/models/1/mmod_human_face_detector.dat

An unhandled exception has been thrown:
Error: Call to undefined function OCA\FaceRecognition\Command\bzopen() in /var/www/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php:191
Stack trace:
#0 /var/www/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php(102): OCA\FaceRecognition\Command\SetupCommand->bunzip2('/tmp/oc_tmp_6Hx...', '/var/www/nextcl...')
#1 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\SetupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#7 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
`

### Steps to reproduce
Only the last step remains 
`sudo -u www-data php occ face:setup`

### Server configuration

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
Passed
* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
Passed
* **PHP version:**
7.2
* **Web server:**
Apache2
* **Database:**
MariaDB
* **Nextcloud version:**
18
### Client configuration

* **Operating system:**
Ubuntu Budgie

**Comment by ltotsas** [comment]
Missing php-bz2 package
