### ISSUE TITLE
System Memory reported as Unknown, will not run Background_Job

### ISSUE THREAD

**Issue by ytc-1** [matiasdelellis/facerecognition#415]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

php occ -vvv face:backgroun_job -u PicTest -t 900
should start recognition process

### Actual behaviour

Tells me there is not enought RAM
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        System: SunOS
        System memory: Unknown
        PHP Memory Limit: 2147483648
        Your system does not meet the minimum of memory requirements.

Basically, the PHP code is not returning the amount of RAM available.
What code is it using that I can fudge from the OS level as I presume it does not know how to get the ram in a Solaris zone.

### Steps to reproduce
1. Install dlib/pdlib https://github.com/goodspb/pdlib
2. Ran make test (worked)
3. Updated memory_limit = 4096M in php.ini
4. Installed face recognition and enabled
5. Ran a test on CLI against a test user
6. 

### Server configuration

* **Operating system:**
Solaris 11.4 ,NC runs in a zone
Hardware has 48Gb RAM
* **Pdlib version:**
1.0.2

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
* Won't installl
Welcome to pdlib min test suite for Facerecognition app...

First we try to open the models... Done

Processing file: input/Big Bang Theory.jpg
PHP Fatal error:  Uncaught Exception: jpeg_loader: error while loading image: Wrong JPEG library version: library is 62, caller expects 80 in /var/tmp/pdlib-min-test-suite-master/scripts/face_detect.php:35
Stack trace:
#0 /var/tmp/pdlib-min-test-suite-master/scripts/face_detect.php(35): CnnFaceDetection->detect('input/Big Bang ...')
#1 /var/tmp/pdlib-min-test-suite-master/scripts/face_detect.php(53): findFaces('input/Big Bang ...')
#2 {main}
  thrown in /var/tmp/pdlib-min-test-suite-master/scripts/face_detect.php on line 35
*** Error code 255
make: Fatal error: Command failed for target `php-test'

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**
7.3
* **Web server:**
Apache24
* **Database:**
MySQL
* **Nextcloud version:**
19.0.6
### Client configuration

* **Browser:**
N/A
* **Operating system:**
Solaris 11.4
#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>
1/10 - Executing task CheckRequirementsTask (Check all requirements)
	System: SunOS
	System memory: Unknown
	PHP Memory Limit: 2147483648
	Your system does not meet the minimum of memory requirements.
Face recognition application requires at least 1 GB of system memory.
See https://github.com/matiasdelellis/facerecognition/wiki/Performance-analysis-of-DLib%E2%80%99s-CNN-face-detection for more details

Fill an issue here if that doesn't help: https://github.com/matiasdelellis/facerecognition/issues
Task CheckRequirementsTask signalled we should not continue, bailing out
```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by matiasdelellis** [comment]
Hi @ytc-1 
Memory management is very important in this application since it can be a very intensive task and consume a lot of memory. And therefore, we must make sure we know the system memory..
Unfortunately, now this function is only implemented for Linux, since it is the only thing I have experience..

https://github.com/matiasdelellis/facerecognition/blob/master/lib/Helper/MemoryLimits.php#L96

Of course happy to accept patches for other architectures..
Sorry I don't have a better answer today .. :disappointed:

**Comment by ytc-1** [comment]
I don't code these days, what is it that is needed to understand the memory?

**Comment by b10102016** [comment]
Hi @ytc-1 

For workaround, edit the file $(NEXTCLOUD_APPS)/facerecognition/lib/Helper/MemoryLimits.php.

```
 79         public static function getSystemMemory(): float {
 80                 if (php_uname("s") !== "Linux")
 81                         return  -1; // change the return value to match your system memory, unit in byte
```

**Comment by ytc-1** [comment]
> Hi @ytc-1
> 
> For workaround, edit the file $(NEXTCLOUD_APPS)/facerecognition/lib/Helper/MemoryLimits.php.
> 
> ```
>  79         public static function getSystemMemory(): float {
>  80                 if (php_uname("s") !== "Linux")
>  81                         return  -1; // change the return value to match your system memory, unit in byte
> ```
> 
> Then run the command, `./occ app:update facerecognition`

That moved me on, thanks.

But now I have another error message for each picture. (below) 
---8<
Processing image /nextcloud/server/nextcloud/data/bruce/files/Pictures/TwoPegsToPatagonia/Ecuador/P1010706.JPG
        Faces found: 0. Image will be skipped because of the following error: Error during image resize
        RuntimeException: Error during image resize in /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php:153
Stack trace:
#0 /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(125): OCA\FaceRecognition\Helper\TempImage->resizeImage()
#1 /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#2 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(203): OCA\FaceRecognition\Helper\TempImage->__construct('/nextcloud/serv...', 'image/png', -1, 512)
#3 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage(Object(OCA\FaceRecognition\Db\Image))
#4 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(120): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#5 /var/www/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(900, true, Object(OC\User\User), NULL)
#6 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#12 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#13 {main}
yielding
---8<

**Comment by ytc-1** [comment]
FYI, if you want me to test any code to be specific to Solaris then I am happy to test it. Any changes would then be most likely to work woth SmartOS or any other OpenSolaris (Illumos) derivatives.
