### ISSUE TITLE
An unhandled exception has been thrown

### ISSUE THREAD

**Issue by derritter88** [matiasdelellis/facerecognition#478]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

All availalbe photos/pictures should be analyzed.

### Actual behaviour

It stops processing at a photo.
First of all I was using `sudo -u www-data php -f /var/www/cloud/occ face:background_job -t 900` but I ran into a timout.
Then I was using `sudo -u www-data php -f /var/www/cloud/occ face:background_job -t 9000` - timeout but later.
Now I was using `sudo -u www-data php -f /var/www/cloud/occ face:background_job` and ran into error (see below).

### Steps to reproduce
1. Run cronjob as mentioned above.

### Server configuration

* **Operating system:** Ubuntu 20.04

* **Pdlib version:** PHP_PDLIB_VERSION "1.0.2"

* **How is DLib installed:** self compiled

* **How is PDlib installed:** self compiled

* **PHP version:** 7.4-FPM

* **Web server:** Apache/2.4.46

* **Database:** Psql 13

* **Nextcloud version:** 21.01

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
Insert your background log here
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
        Processing image /mnt/cloud/nextcloud/4479F707-255F-465B-9468-9D92669CDB71/files/gf/_G_Referenzen/BILDER-REFERENZLISTE/Seniorenheim_Mank.jpg
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/cloud/lib/private/Files/Filesystem.php:716
Stack trace:
#0 /var/www/cloud/lib/private/legacy/OC_Image.php(645): OC\Files\Filesystem::file_get_contents()
#1 /var/www/cloud/apps/facerecognition/lib/Helper/TempImage.php(112): OC_Image->loadFromFile()
#2 /var/www/cloud/apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#3 /var/www/cloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(203): OCA\FaceRecognition\Helper\TempImage->__construct()
#4 /var/www/cloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage()
#5 /var/www/cloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(136): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute()
#6 /var/www/cloud/apps/facerecognition/lib/Command/BackgroundCommand.php(148): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute()
#7 /var/www/cloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute()
#8 /var/www/cloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#9 /var/www/cloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#10 /var/www/cloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#11 /var/www/cloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#12 /var/www/cloud/console.php(100): OC\Console\Application->run()
#13 /var/www/cloud/occ(11): require_once('/var/www/cloud/...')
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by derritter88** [comment]
Hi @matiasdelellis ,

okay - I'll follow the main issue #295
