### ISSUE TITLE
Error when already using model 4

### ISSUE THREAD

**Issue by ther3zz** [matiasdelellis/facerecognition#523]
### Expected behaviour

Running model 4 through all pictures available should complete without crashing

### Actual behaviour

with 3189 images detected and 267 images left, the application crashes with the following error:
```
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\FaceRecognition\Db\Face::setCreationTime() must be an instance of DateTime, string given, called in /config/www/nextcloud/lib/public/AppFramework/Db/Entity.php on line 73 and defined in /config/www/nextcloud/apps/facerecognition/lib/Db/Face.php:200
Stack trace:
#0 /config/www/nextcloud/lib/public/AppFramework/Db/Entity.php(73): OCA\FaceRecognition\Db\Face->setCreationTime()
#1 /config/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(320): OCP\AppFramework\Db\Entity::fromRow()
#2 /config/www/nextcloud/apps/facerecognition/lib/Db/FaceMapper.php(131): OCP\AppFramework\Db\QBMapper->mapRowToEntity()
#3 /config/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(209): OCA\FaceRecognition\Db\FaceMapper->getOldestCreatedFaceWithoutPerson()
#4 /config/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(117): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->hasNewFacesToRecreate()
#5 /config/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(99): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->createClusterIfNeeded()
#6 /config/www/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(141): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->execute()
#7 /config/www/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(151): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute()
#8 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute()
#9 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /config/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /config/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /config/www/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#13 /config/www/nextcloud/console.php(99): OC\Console\Application->run()
#14 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
```

### Steps to reproduce
1. console into docker
2. run occ face:background_job -t 1200  (time value does not matter)
3. alternatively, run via cron (30 min interval - this also does not matter)

### Server configuration

* **Operating system:**
Docker running on unraid, 4GB memory allowed for PHP

* **Pdlib version:**
1.0.2

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)
**
Test suite ran without issue on first install. Installed using the Hard way steps.

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)**

Test suite ran without issue on first install. Installed using the Hard way steps.

* **PHP version:**
 7.4.24

* **Web server:**
nginx

* **Database:**
mariadb

* **Nextcloud version:**
22.2.0

### Client configuration

* **Browser:**
chrome 94.0.4606.71

* **Operating system:**
Windows 10

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
1/10 - Executing task CheckRequirementsTask (Check all requirements)
        System: Linux
        System memory: 16720756736
        PHP Memory Limit: 4294967296
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
yielding
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
        Skipping stale images removal for user g.sandoval as there is no need for it
        Skipping stale images removal for user kayla as there is no need for it
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Found 6 faces without associated persons for user g.sandoval and model 4
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\FaceRecognition\Db\Face::setCreationTime() must be an instance of DateTime, string given, called in /config/www/nextcloud/lib/public/AppFramework/Db/Entity.php on line 73 and defined in /config/www/nextcloud/apps/facerecognition/lib/Db/Face.php:200
Stack trace:
#0 /config/www/nextcloud/lib/public/AppFramework/Db/Entity.php(73): OCA\FaceRecognition\Db\Face->setCreationTime()
#1 /config/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(320): OCP\AppFramework\Db\Entity::fromRow()
#2 /config/www/nextcloud/apps/facerecognition/lib/Db/FaceMapper.php(131): OCP\AppFramework\Db\QBMapper->mapRowToEntity()
#3 /config/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(209): OCA\FaceRecognition\Db\FaceMapper->getOldestCreatedFaceWithoutPerson()
#4 /config/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(117): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->hasNewFacesToRecreate()
#5 /config/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(99): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->createClusterIfNeeded()
#6 /config/www/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(141): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->execute()
#7 /config/www/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(151): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute()
#8 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute()
#9 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /config/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /config/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /config/www/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#13 /config/www/nextcloud/console.php(99): OC\Console\Application->run()
#14 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
#15 {main}
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Exception: Argument 1 passed to OCA\FaceRecognition\Db\Face::setCreationTime() must be an instance of DateTime, string given, called in /config/www/nextcloud/lib/public/AppFramework/Db/Entity.php on line 73
/config/www/nextcloud/lib/private/AppFramework/App.php - line 156:

OC\AppFramework\Http\Dispatcher->dispatch()

/config/www/nextcloud/lib/private/Route/Router.php - line 301:

OC\AppFramework\App::main()

/config/www/nextcloud/lib/base.php - line 1000:

OC\Route\Router->match()

/config/www/nextcloud/index.php - line 36:

OC::handleRequest()

Caused by TypeError: Argument 1 passed to OCA\FaceRecognition\Db\Face::setCreationTime() must be an instance of DateTime, string given, called in /config/www/nextcloud/lib/public/AppFramework/Db/Entity.php on line 73
/config/www/nextcloud/lib/public/AppFramework/Db/Entity.php - line 73:

OCA\FaceRecognition\Db\Face->setCreationTime()

/config/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php - line 320:

OCP\AppFramework\Db\Entity::fromRow()

/config/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php - line 339:

OCP\AppFramework\Db\QBMapper->mapRowToEntity()

/config/www/nextcloud/apps/facerecognition/lib/Db/FaceMapper.php - line 74:

OCP\AppFramework\Db\QBMapper->findEntities()

/config/www/nextcloud/apps/facerecognition/lib/Controller/FileController.php - line 98:

OCA\FaceRecognition\Db\FaceMapper->findFromFile()

/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:

OCA\FaceRecognition\Controller\FileController->getPersonsFromPath()

/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:

OC\AppFramework\Http\Dispatcher->executeController()

/config/www/nextcloud/lib/private/AppFramework/App.php - line 156:

OC\AppFramework\Http\Dispatcher->dispatch()

/config/www/nextcloud/lib/private/Route/Router.php - line 301:

OC\AppFramework\App::main()

/config/www/nextcloud/lib/base.php - line 1000:

OC\Route\Router->match()

/config/www/nextcloud/index.php - line 36:

OC::handleRequest()
```

</details>

I'm not sure why it would work until the last bit and then crash...
Thank you for the help, I really enjoy this project and would love to have it working flawlessly!

**Comment by matiasdelellis** [comment]
Hi @ther3zz 
You install last commit from git???

There was a lot of effort to improve the control of data types, and it's hard to make sure it works on all databases.. The next version will probably be focused on php 8


Please, try just clone the last stable..
* https://github.com/matiasdelellis/facerecognition/commit/0ff4707c2423b726e1932bd602c16b1c866433a0
