### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by pulsejet** [matiasdelellis/facerecognition#613]
With node 18 on Ubuntu 22.04 (on master).
This might have something to do with using older webpack.

```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/var/www/html/apps/facerecognition/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/html/apps/facerecognition/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/html/apps/facerecognition/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/html/apps/facerecognition/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/html/apps/facerecognition/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/html/apps/facerecognition/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/html/apps/facerecognition/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/var/www/html/apps/facerecognition/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /var/www/html/apps/facerecognition/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/var/www/html/apps/facerecognition/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/html/apps/facerecognition/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.11.0
make: *** [Makefile:102: build-vue] Error 1
```

The solution is to support an older version of openssl, **but this is not good**

```
export NODE_OPTIONS=--openssl-legacy-provider
```

### Expected behaviour

Should build on all systems.

**Comment by BijoyJogi123** [comment]
how to solve this issue??

**Comment by BijoyJogi123** [comment]
yea i got the solution just run `npm install react-scripts@latest`

**Comment by munnokd** [comment]
> yea i got the solution just run `npm install react-scripts@latest`

Yes this worked. 
Thanks for  solution.

**Comment by pooranjoyb** [comment]
> yea i got the solution just run `npm install react-scripts@latest`

If this gives you an error, try with `npm install react-scripts@latest --legacy-peer-deps` 
This will ignore all peerDependencies when installing.

**Comment by coderboy-yash** [comment]
yea i got the solution just run npm install react-scripts@latest it works  @pooranjoyb thanks

**Comment by abidmaqbool20** [comment]
What is the solution to this same issue for VUE JS applications?

**Comment by shivambitm** [comment]
DIDN'T GOT THE SOLUTION DUDE :/

**Comment by 0smir** [comment]
Fix for VueJS is quite easy:
Remove node_modules  and delete package-lock.json, then run npm i

also check your dependencies:
 "devDependencies": {
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-router": "~5.0.0",
    "@vue/cli-plugin-vuex": "~5.0.0",
    "@vue/cli-service": "~5.0.0"
}

this worked for me.
thanks to this guy: https://community.frontity.org/t/error-command-npm-run-build-exited-with-1/6480/7

**Comment by Raheemrana** [comment]
> yea i got the solution just run `npm install react-scripts@latest`

Thanks, it worked

**Comment by Aqzovertable** [comment]
help pls but i use vercel or next .js and have is error

**Comment by matiasdelellis** [comment]
Hi everyone.
Within the last PR just commited a patch that I understand would fix this problem.. You can try again from master or apply this patch. https://github.com/matiasdelellis/facerecognition/commit/650e514a61eef5c35950c978524c0b23e2158f1a


I would appreciate confirmation.. :smiley:

**Comment by pjsheth354** [comment]
It worked for me too. Thank you

**Comment by matiasdelellis** [comment]
It is supposed to be fixed since v0.9.12...  Close this.. In any case we can reopen it.. 😄 

Thanks for the reports. 😬

**Comment by mobinveisy** [comment]
thanks a lot

**Comment by krishcodz** [comment]
> npm install react-scripts@latest

thanks man, it works !

**Comment by Bbasavaraju** [comment]
What is the solution for the same issue in Angular applications?

**Comment by Shira2299** [comment]
what about angular which command i need to run???

**Comment by Anant2101** [comment]
I have the same 
The reason is that actually we have differnt origins for the our frontend and back end , they are not allowed to talk to each other.
Solution : Just open package.json in your front end folder
just add 
"proxy" : "Url for your server"(eg "http://localhost:8000/")
and 
now you dont need to specify url in your code just /api/article.....

**Comment by Anant2101** [comment]
I have the same 
The reason is that actually we have differnt origins for the our frontend and back end , they are not allowed to talk to each other.
Solution : Just open package.json in your front end folder
just add 
"proxy" : "Url for your server"(eg "http://localhost:8000/")
and 
now you dont need to specify url in your code just /api/article.....

**Comment by krishcodz** [comment]
> You can simply use node v16, try NVM for switching between versions easily.

i tried it , it didn't fix the issue

**Comment by shiraz27** [comment]
@krishcodz did you make sure to reload your terminal and check node version before running your app ?

**Comment by krishcodz** [comment]
@shiraz27 i think reloading terminal will not make any change, but i checked node version , it was updated .

**Comment by Ayon-SSP** [comment]
@pulsejet It worked.

![image](https://github.com/matiasdelellis/facerecognition/assets/80549753/aeb90c4b-18e5-43ec-bf21-f2c2cab7e6d2)

**Comment by thirupathireddysify** [comment]
what is the solution for angular application

**Comment by rythmn1111** [comment]
YOU ARE GOD MAN!!! HOW THE HACK DID YOU SOLVE THIS PROBLEM OMG !! SOMEDAY I WANT TO HAVE KNOWLEDGE LIKE YOU BROTHER

**Comment by MalikWaqasS** [comment]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/apple/Documents/react-api/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/apple/Documents/react-api/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/apple/Documents/react-api/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/apple/Documents/react-api/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/apple/Documents/react-api/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/apple/Documents/react-api/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/apple/Documents/react-api/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/apple/Documents/react-api/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/apple/Documents/react-api/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/apple/Documents/react-api/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/apple/Documents/react-api/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/apple/Documents/react-api/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/apple/Documents/react-api/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/apple/Documents/react-api/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/apple/Documents/react-api/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/apple/Documents/react-api/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/apple/Documents/react-api/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.11.0
I found this error how can I fix this

**Comment by AmineZouh** [comment]
> nvm use 16.13.1

Thanks sister, this process resolved the issue for me.

**Comment by pulsejet** [comment]
> > nvm use 16.13.1
> 
> Thanks sister, this process resolved the issue for me.

Umm no. Please stop using EOL software. https://nodejs.org/en/blog/announcements/nodejs16-eol

**Comment by Shahrukh509** [comment]
> yea i got the solution just run `npm install react-scripts@latest`

Worked like a charm , thanks lad

**Comment by Vijayshanthi** [comment]
its working .....good

**Comment by senaldm** [comment]
> > yea i got the solution just run `npm install react-scripts@latest`
> 
> Yes this worked. Thanks for solution.

yep thanks for the help . Now it works

**Comment by Lsayilan3** [comment]
![Ekran görüntüsü 2024-03-31 005115](https://github.com/matiasdelellis/facerecognition/assets/89201301/8c60f47f-c8d6-4d26-a4b1-2f0e4de86882)
Can you help me solve the error for Angular?

⠋ Generating browser application bundles...node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (C:\Users\Levent\source\repos\olur\UIPreparation\UI\node_modules\webpack\lib\NormalModule.js:295:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by pulsejet** [comment]
@matiasdelellis can you lock this thread?

**Comment by matiasdelellis** [comment]
You're right..
Sorry guys. But this report receives a lot of comments totally unrelated to the application I've also noticed this, and at first it seemed to be useful, but there are ten different solutions, when in reality you should simply update your dependencies.
