### ISSUE TITLE
An unhandled exception has been thrown: CompressionService.php:48

### ISSUE THREAD

**Issue by jaleel1618** [matiasdelellis/facerecognition#708]
while running this

docker exec -u www-data -it nextcloud-app php occ face:setup --memory 2000Mb --model 1

i got this error

System memory: 3.5 GB (3747201024B)
Memory assigned to PHP: 2.3 GB (2516582400B)
Minimum value to assign to image processing.: 682.7 MB (715827882B)
Maximum value to assign to image processing.: 2.3 GB (2516582400B)
Maximum memory assigned for image processing: 2 GB (2097152000B)

The model 1 (Default) will be installed
An unhandled exception has been thrown:
Error: Call to undefined function OCA\FaceRecognition\Service\bzopen() in /var/www/html/custom_apps/facerecognition/lib/Service/CompressionService.php:48
Stack trace:
#0 /var/www/html/custom_apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php(163): OCA\FaceRecognition\Service\CompressionService->bunzip2('/tmp/oc_tmp_FWj...', '/var/www/html/d...')
#1 /var/www/html/custom_apps/facerecognition/lib/Command/SetupCommand.php(192): OCA\FaceRecognition\Model\DlibCnnModel\DlibCnnModel->install()
#2 /var/www/html/custom_apps/facerecognition/lib/Command/SetupCommand.php(122): OCA\FaceRecognition\Command\SetupCommand->setupModel(1)
#3 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\SetupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/console.php(100): OC\Console\Application->run()
#9 /var/www/html/occ(11): require_once('/var/www/html/c...')

System details:
Operating System: Linux 6.1.0-0.deb11.11-amd64 x86_64
CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz (4 cores)
Memory: 3.49 GB

PHP
Version: 8.2.12
Memory limit: 2.3 GB
Max execution time: 3600
Upload max size: 3.9 GB
Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, standard, posix, random, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, sysvsem, zip, pdlib, Zend OPcache

Nextcloud Version
 27.1.3

**Comment by kentarospin98** [comment]
I'm having the same issues: 
```bash
$ ./occ face:setup -m 1

The model 1 (Default) will be installed
An unhandled exception has been thrown:
Error: Call to undefined function OCA\FaceRecognition\Service\bzopen() in /boron0/nextcloud/apps/facerecognition/lib/Service/CompressionService.php:48
Stack trace:
#0 /boron0/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php(163): OCA\FaceRecognition\Service\CompressionService->bunzip2()
#1 /boron0/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php(192): OCA\FaceRecognition\Model\DlibCnnModel\DlibCnnModel->install()
#2 /boron0/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php(122): OCA\FaceRecognition\Command\SetupCommand->setupModel()
#3 /boron0/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\SetupCommand->execute()
#4 /boron0/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#5 /boron0/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#6 /boron0/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#7 /boron0/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#8 /boron0/nextcloud/console.php(100): OC\Console\Application->run()
#9 /boron0/nextcloud/occ(11): require_once('...')
```

**Comment by Windmark9** [comment]
apt install php-bz2
