### ISSUE TITLE
Clustering fails for large number of faces

### ISSUE THREAD

**Issue by WayneBooth** [matiasdelellis/facerecognition#725]
### Expected behaviour

Consumed resources should be related to the number of new faces to process, not the number of faces already processed. Adding 1 new face should take the same processing power, time and memory to process power, the first time a face is processed vs a new face in a database of 99million.

### Actual behaviour

Clustering take exponentially longer the more images are added to the system. So that when there are around 100k images processed, clustering can take in excess of 4-5 hours, (or fail) to add a single new face.

### Steps to reproduce
1.Perform face recognition on images in 10k batches
2.See that the next run, the clusting steps take exponentially longer
3.After 100k images, the clusting will start to fail.

### Server configuration

* **Operating system:**
Linux nas 5.15.0-1032-realtime #35-Ubuntu SMP PREEMPT_RT Tue Jan 24 11:45:03 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Logs
None logged

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
1/8 - Executing task CheckRequirementsTask (Check all requirements)
2/8 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/8 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
4/8 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
5/8 - Executing task CreateClustersTask (Create new persons or update existing persons)
	Face clustering will be recreated with new information or changes
	65831 faces found for clustering
Killed
```
</details>

**Comment by vwbusguy** [comment]
This was fixed for me with #712 in the new release.  The sweet spot for me was setting the batch to 20k.  It runs much faster with a lot less resources and the clusters are closer to without batching.

**Comment by rarealphacat** [comment]
> This was fixed for me with #712 in the new release. The sweet spot for me was setting the batch to 20k. It runs much faster with a lot less resources and the clusters are closer to without batching.

I ran into a type error of  dlib_vector_length():

5/8 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed
        * or you need to have 95% of you images processed
        Use stats command to track progress
yielding
        Face clustering will be created for the first time.
        There are 3020 faces for clustering
        We will cluster with 2 batch(es) of 1510 faces
An unhandled exception has been thrown:
TypeError: dlib_vector_length(): Argument #1 ($x_arg) must be of type array, string given in /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php:311
Stack trace:
#0 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(311): dlib_vector_length()
#1 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(177): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->getNewClusters()
#2 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(90): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->createClusterIfNeeded()
#3 /var/www/html/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(150): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->execute()
#4 /var/www/html/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(192): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute()
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\BackgroundCommand->execute()
#6 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /var/www/html/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#10 /var/www/html/nextcloud/console.php(102): OC\Console\Application->run()
#11 /var/www/html/nextcloud/occ(11): require_once('...')

**Comment by matiasdelellis** [comment]
Hi,
I still have structural changes pending, but in the next version to be released this week, there is a 40% reduction in memory consumption (At least in my tests. 🙈 

I hope this helps!. 😄
