### ISSUE TITLE
Call to undefined function when adding a model

### ISSUE THREAD

**Issue by mosK1T0** [matiasdelellis/facerecognition#748]
### Expected behaviour

`sudo -u www-date php occ face:setup -model 1` should download model 1

### Actual behaviour

I get the following error
```
sudo -u www-data php occ face:setup --model 1
[sudo] password for nc: 

The model 1 (Default) will be installed
An unhandled exception has been thrown:
Error: Call to undefined function OCA\FaceRecognition\Service\bzopen() in /var/www/nextcloud/apps/facerecognition/lib/Service/CompressionService.php:48
Stack trace:
#0 /var/www/nextcloud/apps/facerecognition/lib/Model/DlibCnnModel/DlibCnnModel.php(163): OCA\FaceRecognition\Service\CompressionService->bunzip2()
#1 /var/www/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php(192): OCA\FaceRecognition\Model\DlibCnnModel\DlibCnnModel->install()
#2 /var/www/nextcloud/apps/facerecognition/lib/Command/SetupCommand.php(122): OCA\FaceRecognition\Command\SetupCommand->setupModel()
#3 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\SetupCommand->execute()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#7 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#8 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#9 /var/www/nextcloud/occ(11): require_once('...')
#10 {main}
``` 

### Server configuration

* **Operating system:** Ubuntu22.04

* **Pdlib version:** 1.1.0

* **How is DLib installed:** `pip install dlib` It works with: [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **How is PDlib installed:** It is installed manually. It works wih: [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:** 8.2.15

* **Web server:** appache

* **Database:** mysql

* **Nextcloud version:** 28.0.3

**Comment by mosK1T0** [comment]
Sorry bz2 was not installed correctly because php8.2-bz2 is not in the official ubuntu repos.
