### ISSUE TITLE
Crashes with TypeError: OCA\FaceRecognition\Helper\Euclidean::distance(): Argument #1 ($vector1) must be of type array, string given, called in 

### ISSUE THREAD

**Issue by wojciechczyz** [matiasdelellis/facerecognition#780]
Hey, Thanks for reporting issues back to Nextcloud Face Recognition. Please, try to complete this report in detail so we can help you easier. :smile:

Make sure you read all the [documentation](https://github.com/matiasdelellis/facerecognition/wiki), and the [FAQ](https://github.com/matiasdelellis/facerecognition/wiki/FAQ), and that the issue has not been reported before. :wink:

### Expected behaviour

when running:

php occ face:background_job --cluster-mode

It starts clustering and then crashes:
1/3 - Executing task CheckRequirementsTask (Check all requirements)
2/3 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/3 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Face clustering will be created for the first time.
        There are 47 faces for clustering
An unhandled exception has been thrown:

### Actual behaviour

Crashes with error:
42b5095134e3:/var/www/html$ php occ face:background_job --cluster-mode
1/3 - Executing task CheckRequirementsTask (Check all requirements)
2/3 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/3 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Face clustering will be created for the first time.
        There are 47 faces for clustering
An unhandled exception has been thrown:
TypeError: OCA\FaceRecognition\Helper\Euclidean::distance(): Argument #1 ($vector1) must be of type array, string given, called in /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php on line 336 and defined in /var/www/html/custom_apps/facerecognition/lib/Helper/Euclidean.php:24
Stack trace:
#0 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(336): OCA\FaceRecognition\Helper\Euclidean::distance('[-0.08935702592...', '[-0.08935702592...')
#1 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(177): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->getNewClusters(Array)
#2 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(90): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->createClusterIfNeeded('admin')
#3 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/BackgroundService.php(150): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#4 /var/www/html/custom_apps/facerecognition/lib/Command/BackgroundCommand.php(192): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(0, false, NULL, NULL, 'cluster-mode')
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(102): OC\Console\Application->run()
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
#12 {main}42b5095134e3:/var/www/html$ 

### Server configuration

* **Operating system:**

docker setup with external container

* **Pdlib version:**

* **How is DLib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

docker setup with external container

* **How is PDlib installed:** Make sure it is working correctly with this [tool](https://github.com/matiasdelellis/pdlib-min-test-suite)

* **PHP version:**

* **Web server:**

* **Database:**

* **Nextcloud version:**

29.0.8

### Client configuration

* **Browser:**

Chrome

* **Operating system:**

Docker under Proxmox

#### Background task log with debug.
<details>
<summary>sudo -u apache php occ -vvv face:background_job</summary>

```
1/8 - Executing task CheckRequirementsTask (Check all requirements)        System: Linux
        System memory: 33227206656        PHP Memory Limit: 2147483648        Clustering backend: PHP (Not recommended.)
        Image Backend: Imaginary        Imaginary version: dev
2/8 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/8 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
yielding
4/8 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
        Skipping stale images removal for user admin as there is no need for it
        Skipping stale images removal for user wojtek as there is no need for it
5/8 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Face clustering will be created for the first time.
        There are 47 faces for clustering
        We will cluster with 1 batch(es) of 47 faces
An unhandled exception has been thrown:
TypeError: OCA\FaceRecognition\Helper\Euclidean::distance(): Argument #1 ($vector1) must be of type array, string given, called in /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php on line 336 and defined in /var/www/html/custom_apps/facerecognition/lib/Helper/Euclidean.php:24
Stack trace:
#0 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(336): OCA\FaceRecognition\Helper\Euclidean::distance('[-0.08935702592...', '[-0.08935702592...')
#1 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(177): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->getNewClusters(Array)
#2 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(90): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->createClusterIfNeeded('admin')
#3 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/BackgroundService.php(150): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#4 /var/www/html/custom_apps/facerecognition/lib/Command/BackgroundCommand.php(192): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(0, true, NULL, NULL, 'default-mode')
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(102): OC\Console\Application->run()
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
42b
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ewok2** [comment]
Hello, I get the same behaviour
Face recognation 0.9.51
NC 29.0.8
Pdlib tested Ok

When launching : 
`sudo -u www-data php /var/www/nextcloud/occ face:background_job`
after a 
`sudo -u www-data php /var/www/nextcloud/occ face:reset --all`
it start analyse the picture and stop after all picture has been analysed
With the stat command : 
```
sudo -u www-data php /var/www/nextcloud/occ face:stats
+----------------+--------+-----------+-------+----------+---------+
| User           | Images | Processed | Faces | Clusters | Persons |
+----------------+--------+-----------+-------+----------+---------+
| user1           | 224    | 224       | 263   | 0        | 0       |
+----------------+--------+-----------+-------+----------+---------+
```
 but when launching again 
`sudo -u www-data php /var/www/nextcloud/occ face:background_job`
I get
```
1/8 - Executing task CheckRequirementsTask (Check all requirements)
2/8 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/8 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
4/8 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
5/8 - Executing task CreateClustersTask (Create new persons or update existing persons)
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
	Face clustering will be created for the first time.
	There are 263 faces for clustering
An unhandled exception has been thrown:
TypeError: dlib_vector_length(): Argument #1 ($x_arg) must be of type array, string given in /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php:311
Stack trace:
#0 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(311): dlib_vector_length()
#1 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(177): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->getNewClusters()
#2 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(90): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->createClusterIfNeeded()
#3 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(150): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->execute()
#4 /var/www/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(192): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute()
#5 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\BackgroundCommand->execute()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#10 /var/www/nextcloud/console.php(102): OC\Console\Application->run()
#11 /var/www/nextcloud/occ(11): require_once('...')
```

The first time I had installed Face recognation it has worked, but after changing the setting on the face detection in NC interface and perform a reset it does not works anymore?

Any idea why?

**Comment by ewok2** [comment]
PS : I initialy test it with a higher number of picture (more than 20 000 picture) but for the last test I perform it on a small number :-)

**Comment by nordscan** [comment]
hi, the same (i tried it maybe a year ago and it was wotking) now:

```terminal
1/8 - Executing task CheckRequirementsTask (Check all requirements)
2/8 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/8 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
4/8 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
5/8 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Face clustering will be recreated with new information or changes
        There are 7635 faces for clustering
An unhandled exception has been thrown:
TypeError: OCA\FaceRecognition\Helper\Euclidean::distance(): Argument #1 ($vector1) must be of type array, string given, called in /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php on line 336 and defined in /var/www/html/custom_apps/facerecognition/lib/Helper/Euclidean.php:24
Stack trace:
#0 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(336): OCA\FaceRecognition\Helper\Euclidean::distance('[-0.10269370675...', '[-0.10269370675...')
#1 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(177): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->getNewClusters(Array)
#2 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(90): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->createClusterIfNeeded('nordscan')
#3 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/BackgroundService.php(150): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#4 /var/www/html/custom_apps/facerecognition/lib/Command/BackgroundCommand.php(192): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(0, false, Object(OC\User\User), NULL, 'default-mode')
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(102): OC\Console\Application->run()
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**Comment by ewok2** [comment]
@Oski19831  thanks your workaroud seem's to works for me !

**Comment by vwbusguy** [comment]
> I can confirm this Bug also. It is a WorkArround to manuel convert the json_string to an array.
> 
> I don´t know if this is a Problem with PHP. I use PHP8.2 and run it on a RPI4 with ARM64-CPU.
> 
> for me it work to edit the CreateClusterTaks.php on Line 311
> 
> `$distance = dlib_vector_length($face1->descriptor, $face2->descriptor);` to
> 
> `if(!is_array($face1->descriptor)) { $face1->descriptor = json_decode($face1->descriptor, true); } if(!is_array($face2->descriptor)) { $face2->descriptor = json_decode($face2->descriptor, true); } $distance = dlib_vector_length($face1->descriptor, $face2->descriptor);`
> 
> I hope this help temporaly...

Heck yes!  Maybe submit a Pull Request for this?

**Comment by Oski19831** [comment]
I never wrote Code for NC. So i think it is better Solution to change Code in DB-Object. But i don´t know the relation between NC and Entity - Class in NC. I think this Code is better in /lib/Db/Face.php. Or a function there... and call the function in CreateClusterTask.php ... But if it is helfull for you i will change the code...

**Comment by warriorcookie** [comment]
Same issue here.

Noticed Face Recognition was hung at Analyzing images - 31779 images detected - 339 images in queue - Ends approximately in 26 minutes.

went to CLI and executed the following:
```
:~$ sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ face:background_job
1/8 - Executing task CheckRequirementsTask (Check all requirements)
2/8 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/8 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
4/8 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
5/8 - Executing task CreateClustersTask (Create new persons or update existing persons)
	Face clustering will be created for the first time.
	There are 2 faces for clustering
An unhandled exception has been thrown:
TypeError: OCA\FaceRecognition\Helper\Euclidean::distance(): Argument #1 ($vector1) must be of type array, string given, called in /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php on line 336 and defined in /var/www/html/custom_apps/facerecognition/lib/Helper/Euclidean.php:24
Stack trace:
#0 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(336): OCA\FaceRecognition\Helper\Euclidean::distance('[-0.04276097938...', '[-0.04276097938...')
#1 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(177): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->getNewClusters(Array)
#2 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php(90): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->createClusterIfNeeded('admin')
#3 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/BackgroundService.php(150): OCA\FaceRecognition\BackgroundJob\Tasks\CreateClustersTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#4 /var/www/html/custom_apps/facerecognition/lib/Command/BackgroundCommand.php(192): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(0, false, NULL, NULL, 'default-mode')
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(183): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(87): OC\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
#12 {main}
```

**Comment by Oski19831** [comment]
Same here. $faces returns a String instead of an array. 

So for WorkArround add a function in /lib/Db/Face.php
`function getDescriptorArray(): array {
if(is_array($this->descriptor)) {
return $this->descriptor; 
} else {
return jsond_decode($this->descriptor, true);
}
}`

and change each $face1['descriptor'] and $face2['descriptor'] to $face1->getDescriptorArray() and $face2->getDescriptorArray() in /lib/BackgroundJob/Tasks/CreateClusterTask.php

Or change my Solution above to your Code in CreateClusterTask.php

This is my Solutiion for this Issue.

This schould work as WorkArround or Wait until the Issue is fixed... I hope i could help you.

**Comment by tuxArg** [comment]
Probably related I've got this error:
```
An unhandled exception has been thrown:
Error: Call to a member function getTimestamp() on string in /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/CreateClustersTask.php:232
```

**Comment by nordscan** [comment]
#https://github.com/matiasdelellis/facerecognition/issues/781

**Comment by Oski19831** [comment]
hello @mrmipo .

change $face1->descriptor to $face1->getDescriptorArray(). that should call the function in Class Face.php and returned an array and not the String from the DB. Try it. 

@tuxArg 

For you the WorkArround ist like the Same. You get the TimeString instead a DateTime-Object. So it must be converted before call getTimestamp().

**Comment by tuxArg** [comment]
> For you the WorkArround ist like the Same. You get the TimeString instead a DateTime-Object. So it must be converted before call getTimestamp().

I did it this way: https://github.com/matiasdelellis/facerecognition/issues/781#issuecomment-2429163804

**Comment by mrmipo** [comment]
> hello @mrmipo .
> 
> change $face1->descriptor to $face1->getDescriptorArray(). that should call the function in Class Face.php and returned an array and not the String from the DB. Try it.
> 
> EDIT:
> 
> And you don´t proof again in CreateTaskCluster.php if $facex->descriptor is an array. you proof it also in the function getDescriptorArray() in Face.php.
> 
> @tuxArg
> 
> For you the WorkArround ist like the Same. You get the TimeString instead a DateTime-Object. So it must be converted before call getTimestamp().

Hi Oski19831

Ok I finally fix this issue and it's look like no it's working fine (manage new image/face and creating clustering) but without getDescriptorArray() as I was not able to understand how it's should be done. But I use your solution from beginning and from issue that I create. So I only modify one file CreateClustersTask.php . Output from diff:

```
$ diff CreateClustersTask.php_org CreateClustersTask.php
--- CreateClustersTask.php_org
+++ CreateClustersTask.php
@@ -229,10 +229,16 @@

                // We have some faces, but not that many, let's see when oldest one is generated.
                $oldestFace = $this->faceMapper->getOldestCreatedFaceWithoutPerson($userId, $modelId);
-               $oldestFaceTimestamp = $oldestFace->creationTime->getTimestamp();
+               if (is_string($oldestFace->creationTime)) {
+                       $oldestFaceTimestamp = strtotime($oldestFace->creationTime);
+                       $oldestFaceFormat=$oldestFace->creationTime;
+               } else {
+                       $oldestFaceTimestamp = $oldestFace->creationTime->getTimestamp();
+                       $oldestFaceFormat=$oldestFace->creationTime->format('Y-m-d H:i:s');
+               }
                $currentTimestamp = (new \DateTime())->getTimestamp();
                $this->logDebug(sprintf('Oldest face without persons for user %s and model %d is from %s',
-                               $userId, $modelId, $oldestFace->creationTime->format('Y-m-d H:i:s')));
+                               $userId, $modelId, $oldestFaceFormat));

                // todo: get rid of magic numbers (move to config)
                if ($currentTimestamp - $oldestFaceTimestamp > 2 * 60 * 60)
@@ -308,6 +314,12 @@
                                        if (!isset($face2->descriptor)) {
                                                continue;
                                        }
+                                       if (!is_array($face1->descriptor)) {
+                                               $face1->descriptor = json_decode($face1->descriptor, true);
+                                       }
+                                       if (!is_array($face2->descriptor)) {
+                                               $face2->descriptor = json_decode($face2->descriptor, true);
+                                       }
                                        $distance = dlib_vector_length($face1->descriptor, $face2->descriptor);
                                        if ($distance < $sensitivity) {
                                                $edges[] = array($i, $j);
@@ -333,6 +345,12 @@
                                        if (!isset($face2->descriptor)) {
                                                continue;
                                        }
+                                       if (!is_array($face1->descriptor)) {
+                                                $face1->descriptor = json_decode($face1->descriptor, true);
+                                        }
+                                        if (!is_array($face2->descriptor)) {
+                                                $face2->descriptor = json_decode($face2->descriptor, true);
+                                        }
                                        $distance = Euclidean::distance($face1->descriptor, $face2->descriptor);
                                        if ($distance < $sensitivity) {
                                                $edges[] = array($i, $j);
```

Really thanks for your help

**Comment by Oski19831** [comment]
Top no thanks. I test a modification which is easyer... i post an update if it pass the test....

**Comment by tocopaxi** [comment]
> I can confirm this Bug also. It is a WorkArround to manuel convert the json_string to an array.
> 
> I don´t know if this is a Problem with PHP. I use PHP8.2 and run it on a RPI4 with ARM64-CPU.
> 
> for me it work to edit the CreateClusterTaks.php on Line 311
> 
> `$distance = dlib_vector_length($face1->descriptor, $face2->descriptor);` to
> 
> `if(!is_array($face1->descriptor)) { $face1->descriptor = json_decode($face1->descriptor, true); } if(!is_array($face2->descriptor)) { $face2->descriptor = json_decode($face2->descriptor, true); } $distance = dlib_vector_length($face1->descriptor, $face2->descriptor);`
> 
> I hope this help temporaly...

I had the same issue and can confirm that this solution by @Oski19831 works for me as well - thanks :)

**Comment by matiasdelellis** [comment]
Hi everyone,
I will soon release a version compatible with NC30, and I was thinking of deprecating NC29 since I can't test it. However, I see that some Nextcloud update is causing problems in NC29 with this application as well.. 😞 

As I said, I couldn't reproduce this problem in my installations or in testing. However, I am trying the fix suggested by [Oski19831](https://github.com/matiasdelellis/facerecognition/issues/780#issuecomment-2433105764), and in my case it does not cause any problems.

Here I leave you a tarball with all the changes introduced for nexctloud 30 and still compatible with nc29 plus this patch.

* [facerecognition.tar.gz](https://github.com/user-attachments/files/17646881/facerecognition.tar.gz)

If you test it and confirm that it works, I will add it and release the update this week.. 😉

**Comment by benneti** [comment]
I already had the change https://github.com/matiasdelellis/facerecognition/issues/780#issuecomment-2433105764 on nc29 but installing the tar.gz did not seem to have broken anything.

**Comment by Oski19831** [comment]
> Hi everyone, I will soon release a version compatible with NC30, and I was thinking of deprecating NC29 since I can't test it. However, I see that some Nextcloud update is causing problems in NC29 with this application as well.. 😞
> 
> As I said, I couldn't reproduce this problem in my installations or in testing. However, I am trying the fix suggested by [Oski19831](https://github.com/matiasdelellis/facerecognition/issues/780#issuecomment-2433105764), and in my case it does not cause any problems.
> 
> Here I leave you a tarball with all the changes introduced for nexctloud 30 and still compatible with nc29 plus this patch.
> 
> * [facerecognition.tar.gz](https://github.com/user-attachments/files/17646881/facerecognition.tar.gz)
> 
> If you test it and confirm that it works, I will add it and release the update this week.. 😉

I can confirm that this Version run on NC 29.

**Comment by Oski19831** [comment]
Hi @priyankub. This error is not related to this App it think. Nextcloud cannot load the Data of one of your pictures and it retrunted null. 

you can proof against null and return null. But i don´t know what does it with the response. But you can try it with a Line in 129 in /var/www/html/custom_apps/facerecognition/lib/Controller/FaceController.php
you will miss a Thumb than i think.
`if($img->data === null) return;`

**Comment by priyankub** [comment]
I rewrote that entire function to:

```
public function getThumb($id, $size) {
    $face = $this->faceMapper->find($id);
    if ($face === null) {
        return new JSONResponse([], Http::STATUS_NOT_FOUND);
    }

    $image = $this->imageMapper->find($this->userId, $face->getImage());
    if ($image === null) {
        return new JSONResponse([], Http::STATUS_NOT_FOUND);
    }

    $fileId = $image->getFile();
    $userFolder = $this->rootFolder->getUserFolder($this->userId);
    $nodes = $userFolder->getById($fileId);
    $file = $nodes[0];

    $ownerView = new \OC\Files\View('/' . $this->userId . '/files');
    $path = $userFolder->getRelativePath($file->getPath());

    $img = new OCP_Image();
    $fileName = $ownerView->getLocalFile($path);

    try {
        // Attempt to load the image
        if (!$img->loadFromFile($fileName)) {
            $this->logger->warning("Failed to load image file: {$fileName} for user {$this->userId}, face ID: {$id}");
            return new DataDisplayResponse('', Http::STATUS_OK, ['Content-Type' => 'text/plain']);
        }

        $img->fixOrientation();

        $x = $face->getX();
        $y = $face->getY();
        $w = $face->getWidth();
        $h = $face->getHeight();

        $padding = $h * 0.35;
        $x -= $padding;
        $y -= $padding;
        $w += $padding * 2;
        $h += $padding * 2;

        if ($this->settingsService->getObfuscateFaces()) {
            $this->hipsterize($img, $face);
        }

        $img->crop($x, $y, $w, $h);
        $img->scaleDownToFit($size, $size);

        // Retrieve image data
        $data = $img->getData();

        if ($data === null) {
            $this->logger->warning("Processed image data is null for face ID: {$id}, user: {$this->userId}");
            return new DataDisplayResponse('', Http::STATUS_OK, ['Content-Type' => 'text/plain']);
        }

        $resp = new DataDisplayResponse($data, Http::STATUS_OK, ['Content-Type' => $img->mimeType()]);
        $resp->setETag((string)crc32($data));
        $resp->cacheFor(7 * 24 * 60 * 60); // Cache for 7 days
        $resp->setLastModified(new \DateTime('now', new \DateTimeZone('GMT')));

        return $resp;
    } catch (\Exception $e) {
        $this->logger->error("Error processing thumbnail for face ID: {$id}, user: {$this->userId}. Exception: {$e->getMessage()}");
        return new JSONResponse(['error' => 'Unable to generate thumbnail'], Http::STATUS_INTERNAL_SERVER_ERROR);
    }
}
```
